vim.cmd "hi clear"
vim.g.colors_name = "yaru-dark-ish"
vim.o.termguicolors = true

-- Yaru Dark-ish ANSI palette
local c = {
  bg         = "#262626",
  black      = "#303030",
  blue       = "#87AFFF",
  brblack    = "#5E5C64",
  brblue     = "#19B6EE",
  brcyan     = "#87AFFF",
  brgreen    = "#34B948",
  brmag      = "#c590bf",
  brred      = "#FF87AF",
  brwhite    = "#FFFFFF",
  bryellow   = "#FBC16A",
  cyan       = "#75d3f4",
  darkbg     = "#1E1E1E",
  darker     = "#181818",
  fg         = "#C0BFBC",
  gray       = "#504E55",
  green      = "#AFD787",
  magenta    = "#D7AFFF",
  orange     = "#E95420",
  red        = "#EA485C",
  subtext0   = "#9A9996",
  subtext1   = "#B0AFAC",
  surface0   = "#2A2A2A",
  surface1   = "#303030",
  surface2   = "#3D3846",
  white      = "#C0BFBC",
  yellow     = "#FFAF87",
}

local function hi(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- Highlight groups (resolved)
hi("@attribute.c_sharp", { fg = c.bryellow })
hi("@character.special.html", { fg = c.red })
hi("@comment.error", { fg = c.bg, bg = c.red })
hi("@comment.hint", { fg = c.bg, bg = c.blue })
hi("@comment.note", { fg = c.bg, bg = c.blue })
hi("@comment.todo", { fg = c.bg, bg = c.bryellow })
hi("@comment.warning", { fg = c.bg, bg = c.bryellow })
hi("@comment.warning.gitcommit", { fg = c.bryellow })
hi("@constant.builtin", { fg = c.yellow })
hi("@constant.java", { fg = c.brgreen })
hi("@constructor", { fg = c.bryellow })
hi("@constructor.python", { fg = c.cyan })
hi("@field", { fg = c.brcyan })
hi("@function.builtin", { fg = c.yellow })
hi("@function.builtin.bash", { fg = c.red, italic = true })
hi("@function.macro", { fg = c.brmag })
hi("@keyword.export", { fg = c.magenta })
hi("@keyword.function", { fg = c.magenta })
hi("@keyword.import.c", { fg = c.bryellow })
hi("@keyword.import.cpp", { fg = c.bryellow })
hi("@keyword.operator", { fg = c.magenta })
hi("@keyword.return", { fg = c.magenta })
hi("@label.yaml", { fg = c.bryellow })
hi("@lsp.type.enumMember", { fg = c.brgreen })
hi("@markup", { fg = c.fg })
hi("@markup.environment", { fg = c.brmag })
hi("@markup.environment.name", { fg = c.blue })
hi("@markup.heading", { fg = c.blue })
hi("@markup.heading.1.delimiter.vimdoc", { fg = c.bg, bg = c.bg, sp = c.fg, underdouble = true, nocombine = true })
hi("@markup.heading.2.delimiter.vimdoc", { fg = c.bg, bg = c.bg, sp = c.fg, underline = true, nocombine = true })
hi("@markup.heading.markdown", { bold = true })
hi("@markup.italic", { fg = c.red, italic = true })
hi("@markup.link", { fg = c.brcyan })
hi("@markup.link.label", { fg = c.brcyan })
hi("@markup.link.label.html", { fg = c.fg })
hi("@markup.link.url", { fg = c.blue, italic = true, underline = true })
hi("@markup.list", { fg = c.brgreen })
hi("@markup.list.checked", { fg = c.green })
hi("@markup.list.unchecked", { fg = c.brblack })
hi("@markup.math", { fg = c.blue })
hi("@markup.quote", { fg = c.brmag })
hi("@markup.raw", { fg = c.fg })
hi("@markup.strikethrough", { fg = c.fg, strikethrough = true })
hi("@markup.strong", { fg = c.red, bold = true })
hi("@module", { fg = c.bryellow, italic = true })
hi("@namespace", { fg = c.bryellow, italic = true })
hi("@number.css", { fg = c.yellow })
hi("@parameter", { fg = c.brred })
hi("@property", { fg = c.brcyan })
hi("@property.class.css", { fg = c.bryellow })
hi("@property.css", { fg = c.blue })
hi("@property.id.css", { fg = c.bryellow })
hi("@property.scss", { fg = c.blue })
hi("@punctuation.bracket", { fg = c.brblack })
hi("@string.documentation", { fg = c.brgreen })
hi("@string.escape", { fg = c.brmag })
hi("@string.plain.css", { fg = c.fg })
hi("@string.regex", { fg = c.brmag })
hi("@string.regexp", { fg = c.brmag })
hi("@string.special.path.gitignore", { fg = c.fg })
hi("@string.special.symbol", { fg = c.bryellow })
hi("@string.special.symbol.ruby", { fg = c.bryellow })
hi("@string.special.url", { fg = c.blue, italic = true, underline = true })
hi("@string.special.url.html", { fg = c.green })
hi("@symbol", { fg = c.bryellow })
hi("@symbol.ruby", { fg = c.bryellow })
hi("@tag", { fg = c.blue })
hi("@tag.attribute", { fg = c.bryellow, italic = true })
hi("@tag.builtin", { fg = c.blue })
hi("@tag.delimiter", { fg = c.brgreen })
hi("@text", { fg = c.fg })
hi("@text.danger", { fg = c.bg, bg = c.red })
hi("@text.emphasis", { fg = c.red, italic = true })
hi("@text.environment", { fg = c.brmag })
hi("@text.environment.name", { fg = c.blue })
hi("@text.literal", { fg = c.green })
hi("@text.math", { fg = c.blue })
hi("@text.note", { fg = c.bg, bg = c.blue })
hi("@text.reference", { fg = c.brcyan })
hi("@text.strike", { fg = c.fg, strikethrough = true })
hi("@text.strong", { fg = c.red, bold = true })
hi("@text.title", { fg = c.blue })
hi("@text.todo", { fg = c.bg, bg = c.bryellow })
hi("@text.todo.checked", { fg = c.green })
hi("@text.todo.unchecked", { fg = c.brblack })
hi("@text.warning", { fg = c.bg, bg = c.bryellow })
hi("@type.builtin", { fg = c.magenta })
hi("@type.css", { fg = c.brcyan })
hi("@type.tag.css", { fg = c.blue })
hi("@variable", { fg = c.fg })
hi("@variable.builtin", { fg = c.red })
hi("@variable.member", { fg = c.brcyan })
hi("@variable.parameter", { fg = c.brred })
hi("@variable.parameter.bash", { fg = c.green })
hi("Added", { fg = c.green })
hi("AlphaButtons", { fg = c.brcyan })
hi("AlphaFooter", { fg = c.bryellow, italic = true })
hi("AlphaHeader", { fg = c.blue })
hi("AlphaHeaderLabel", { fg = c.yellow })
hi("AlphaShortcut", { fg = c.green })
hi("BlinkCmpKind", { fg = c.blue })
hi("BlinkCmpKindClass", { fg = c.bryellow })
hi("BlinkCmpKindColor", { fg = c.red })
hi("BlinkCmpKindConstant", { fg = c.yellow })
hi("BlinkCmpKindConstructor", { fg = c.blue })
hi("BlinkCmpKindCopilot", { fg = c.brgreen })
hi("BlinkCmpKindEnum", { fg = c.bryellow })
hi("BlinkCmpKindEnumMember", { fg = c.brgreen })
hi("BlinkCmpKindEvent", { fg = c.blue })
hi("BlinkCmpKindField", { fg = c.green })
hi("BlinkCmpKindFile", { fg = c.blue })
hi("BlinkCmpKindFolder", { fg = c.blue })
hi("BlinkCmpKindFunction", { fg = c.blue })
hi("BlinkCmpKindInterface", { fg = c.bryellow })
hi("BlinkCmpKindKeyword", { fg = c.magenta })
hi("BlinkCmpKindMethod", { fg = c.blue })
hi("BlinkCmpKindModule", { fg = c.blue })
hi("BlinkCmpKindOperator", { fg = c.cyan })
hi("BlinkCmpKindProperty", { fg = c.blue })
hi("BlinkCmpKindReference", { fg = c.red })
hi("BlinkCmpKindSnippet", { fg = c.bryellow })
hi("BlinkCmpKindStruct", { fg = c.blue })
hi("BlinkCmpKindText", { fg = c.green })
hi("BlinkCmpKindTypeParameter", { fg = c.brred })
hi("BlinkCmpKindUnit", { fg = c.green })
hi("BlinkCmpKindValue", { fg = c.yellow })
hi("BlinkCmpKindVariable", { fg = c.bryellow })
hi("BlinkCmpLabel", { fg = c.brblack })
hi("BlinkCmpLabelDeprecated", { fg = c.gray, strikethrough = true })
hi("BlinkCmpMenuBorder", { fg = c.blue, bg = c.darkbg })
hi("BlinkCmpMenuSelection", { bg = c.surface1, bold = true })
hi("BlinkCmpScrollBarGutter", { bg = c.surface1 })
hi("BlinkCmpScrollBarThumb", { bg = c.gray })
hi("BlinkIndent", { fg = c.surface0 })
hi("BlinkIndentBlue", { fg = c.blue })
hi("BlinkIndentBlueUnderline", { sp = c.blue, underline = true })
hi("BlinkIndentCyan", { fg = c.cyan })
hi("BlinkIndentCyanUnderline", { sp = c.cyan, underline = true })
hi("BlinkIndentGreen", { fg = c.green })
hi("BlinkIndentGreenUnderline", { sp = c.green, underline = true })
hi("BlinkIndentOrange", { fg = c.yellow })
hi("BlinkIndentOrangeUnderline", { sp = c.yellow, underline = true })
hi("BlinkIndentRed", { fg = c.red })
hi("BlinkIndentRedUnderline", { sp = c.red, underline = true })
hi("BlinkIndentScope", { fg = c.brblack })
hi("BlinkIndentViolet", { fg = c.magenta })
hi("BlinkIndentVioletUnderline", { sp = c.magenta, underline = true })
hi("BlinkIndentYellow", { fg = c.bryellow })
hi("BlinkIndentYellowUnderline", { sp = c.bryellow, underline = true })
hi("Bold", { bold = true })
hi("Boolean", { fg = c.yellow })
hi("Changed", { fg = c.blue })
hi("Character", { fg = c.brgreen })
hi("CmpItemAbbr", { fg = c.brblack })
hi("CmpItemAbbrDeprecated", { fg = c.gray, strikethrough = true })
hi("CmpItemAbbrMatch", { fg = c.fg, bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = c.fg, bold = true })
hi("CmpItemKind", { fg = c.blue })
hi("CmpItemKindClass", { fg = c.bryellow })
hi("CmpItemKindColor", { fg = c.red })
hi("CmpItemKindConstant", { fg = c.yellow })
hi("CmpItemKindConstructor", { fg = c.blue })
hi("CmpItemKindCopilot", { fg = c.brgreen })
hi("CmpItemKindEnum", { fg = c.green })
hi("CmpItemKindEnumMember", { fg = c.red })
hi("CmpItemKindEvent", { fg = c.blue })
hi("CmpItemKindField", { fg = c.green })
hi("CmpItemKindFile", { fg = c.blue })
hi("CmpItemKindFolder", { fg = c.blue })
hi("CmpItemKindFunction", { fg = c.blue })
hi("CmpItemKindInterface", { fg = c.bryellow })
hi("CmpItemKindKeyword", { fg = c.red })
hi("CmpItemKindMethod", { fg = c.blue })
hi("CmpItemKindModule", { fg = c.blue })
hi("CmpItemKindOperator", { fg = c.blue })
hi("CmpItemKindProperty", { fg = c.green })
hi("CmpItemKindReference", { fg = c.red })
hi("CmpItemKindSnippet", { fg = c.magenta })
hi("CmpItemKindStruct", { fg = c.blue })
hi("CmpItemKindText", { fg = c.brgreen })
hi("CmpItemKindTypeParameter", { fg = c.blue })
hi("CmpItemKindUnit", { fg = c.green })
hi("CmpItemKindValue", { fg = c.yellow })
hi("CmpItemKindVariable", { fg = c.bryellow })
hi("CmpItemMenu", { fg = c.fg })
hi("ColorColumn", { bg = c.surface0 })
hi("Comment", { fg = c.brblack, italic = true })
hi("ComplHint", { fg = c.subtext0 })
hi("Conceal", { fg = c.brblack })
hi("Conditional", { fg = c.magenta, italic = true })
hi("Constant", { fg = c.yellow })
hi("CurSearch", { fg = c.darkbg, bg = c.red })
hi("Cursor", { fg = c.bg, bg = c.bryellow })
hi("CursorColumn", { bg = c.darkbg })
hi("CursorIM", { fg = c.bg, bg = c.bryellow })
hi("CursorLine", { bg = c.surface0 })
hi("CursorLineNr", { fg = c.brcyan })
hi("DapBreakpoint", { fg = c.red })
hi("DapBreakpointCondition", { fg = c.bryellow })
hi("DapBreakpointRejected", { fg = c.magenta })
hi("DapLogPoint", { fg = c.cyan })
hi("DapStopped", { fg = c.brred })
hi("DapUIBreakpointsCurrentLine", { fg = c.green, bold = true })
hi("DapUIBreakpointsDisabledLine", { fg = c.surface2 })
hi("DapUIBreakpointsInfo", { fg = c.green })
hi("DapUIBreakpointsPath", { fg = c.cyan })
hi("DapUIDecoration", { fg = c.cyan })
hi("DapUILineNumber", { fg = c.cyan })
hi("DapUIModifiedValue", { fg = c.yellow })
hi("DapUIPlayPause", { fg = c.green })
hi("DapUIRestart", { fg = c.green })
hi("DapUIScope", { fg = c.cyan })
hi("DapUISource", { fg = c.brcyan })
hi("DapUIStepBack", { fg = c.blue })
hi("DapUIStepInto", { fg = c.blue })
hi("DapUIStepOut", { fg = c.blue })
hi("DapUIStepOver", { fg = c.blue })
hi("DapUIStop", { fg = c.red })
hi("DapUIStoppedThread", { fg = c.cyan })
hi("DapUIThread", { fg = c.green })
hi("DapUIType", { fg = c.magenta })
hi("DapUIUnavailable", { fg = c.surface1 })
hi("DapUIValue", { fg = c.cyan })
hi("DapUIVariable", { fg = c.fg })
hi("DapUIWatchesEmpty", { fg = c.brred })
hi("DapUIWatchesError", { fg = c.brred })
hi("DapUIWatchesValue", { fg = c.green })
hi("DapUIWinSelect", { fg = c.yellow })
hi("DashboardCenter", { fg = c.green })
hi("DashboardDesc", { fg = c.blue })
hi("DashboardFiles", { fg = c.brcyan })
hi("DashboardFooter", { fg = c.bryellow, italic = true })
hi("DashboardHeader", { fg = c.blue })
hi("DashboardIcon", { fg = c.brmag, bold = true })
hi("DashboardKey", { fg = c.yellow })
hi("DashboardMruTitle", { fg = c.cyan })
hi("DashboardProjectTitle", { fg = c.cyan })
hi("DashboardShortCut", { fg = c.brmag })
hi("Delimiter", { fg = c.brblack })
hi("DiagnosticDeprecated", { sp = c.bryellow, strikethrough = true })
hi("DiagnosticError", { fg = c.red, italic = true })
hi("DiagnosticFloatingError", { fg = c.red })
hi("DiagnosticFloatingHint", { fg = c.brgreen })
hi("DiagnosticFloatingInfo", { fg = c.cyan })
hi("DiagnosticFloatingOk", { fg = c.green })
hi("DiagnosticFloatingWarn", { fg = c.bryellow })
hi("DiagnosticHint", { fg = c.brgreen, italic = true })
hi("DiagnosticInfo", { fg = c.cyan, italic = true })
hi("DiagnosticOk", { fg = c.green, italic = true })
hi("DiagnosticSignError", { fg = c.red })
hi("DiagnosticSignHint", { fg = c.brgreen })
hi("DiagnosticSignInfo", { fg = c.cyan })
hi("DiagnosticSignOk", { fg = c.green })
hi("DiagnosticSignWarn", { fg = c.bryellow })
hi("DiagnosticUnderlineError", { sp = c.red, underline = true })
hi("DiagnosticUnderlineHint", { sp = c.brgreen, underline = true })
hi("DiagnosticUnderlineInfo", { sp = c.cyan, underline = true })
hi("DiagnosticUnderlineOk", { sp = c.green, underline = true })
hi("DiagnosticUnderlineWarn", { sp = c.bryellow, underline = true })
hi("DiagnosticVirtualTextError", { fg = c.red, bg = c.surface0, italic = true })
hi("DiagnosticVirtualTextHint", { fg = c.brgreen, bg = c.surface0, italic = true })
hi("DiagnosticVirtualTextInfo", { fg = c.cyan, bg = c.surface0, italic = true })
hi("DiagnosticVirtualTextOk", { fg = c.green, bg = c.surface0, italic = true })
hi("DiagnosticVirtualTextWarn", { fg = c.bryellow, bg = c.surface0, italic = true })
hi("DiagnosticWarn", { fg = c.bryellow, italic = true })
hi("DiffAdd", { bg = c.surface0 })
hi("DiffChange", { bg = c.surface0 })
hi("DiffDelete", { bg = c.surface0 })
hi("DiffText", { bg = c.surface1 })
hi("Directory", { fg = c.blue })
hi("DropBarIconUISeparator", { fg = c.brblack })
hi("DropBarKindArray", { fg = c.fg })
hi("DropBarKindBoolean", { fg = c.fg })
hi("DropBarKindBreakStatement", { fg = c.fg })
hi("DropBarKindCall", { fg = c.fg })
hi("DropBarKindCaseStatement", { fg = c.fg })
hi("DropBarKindClass", { fg = c.fg })
hi("DropBarKindConstant", { fg = c.fg })
hi("DropBarKindConstructor", { fg = c.fg })
hi("DropBarKindContinueStatement", { fg = c.fg })
hi("DropBarKindDeclaration", { fg = c.fg })
hi("DropBarKindDelete", { fg = c.fg })
hi("DropBarKindDoStatement", { fg = c.fg })
hi("DropBarKindElseStatement", { fg = c.fg })
hi("DropBarKindEnum", { fg = c.fg })
hi("DropBarKindEnumMember", { fg = c.fg })
hi("DropBarKindEvent", { fg = c.fg })
hi("DropBarKindField", { fg = c.fg })
hi("DropBarKindFile", { fg = c.fg })
hi("DropBarKindFolder", { fg = c.fg })
hi("DropBarKindForStatement", { fg = c.fg })
hi("DropBarKindFunction", { fg = c.fg })
hi("DropBarKindIdentifier", { fg = c.fg })
hi("DropBarKindIfStatement", { fg = c.fg })
hi("DropBarKindInterface", { fg = c.fg })
hi("DropBarKindKeyword", { fg = c.fg })
hi("DropBarKindList", { fg = c.fg })
hi("DropBarKindMacro", { fg = c.fg })
hi("DropBarKindMarkdownH1", { fg = c.fg })
hi("DropBarKindMarkdownH2", { fg = c.fg })
hi("DropBarKindMarkdownH3", { fg = c.fg })
hi("DropBarKindMarkdownH4", { fg = c.fg })
hi("DropBarKindMarkdownH5", { fg = c.fg })
hi("DropBarKindMarkdownH6", { fg = c.fg })
hi("DropBarKindMethod", { fg = c.fg })
hi("DropBarKindModule", { fg = c.fg })
hi("DropBarKindNamespace", { fg = c.fg })
hi("DropBarKindNull", { fg = c.fg })
hi("DropBarKindNumber", { fg = c.fg })
hi("DropBarKindObject", { fg = c.fg })
hi("DropBarKindOperator", { fg = c.fg })
hi("DropBarKindPackage", { fg = c.fg })
hi("DropBarKindProperty", { fg = c.fg })
hi("DropBarKindReference", { fg = c.fg })
hi("DropBarKindRepeat", { fg = c.fg })
hi("DropBarKindScope", { fg = c.fg })
hi("DropBarKindSpecifier", { fg = c.fg })
hi("DropBarKindStatement", { fg = c.fg })
hi("DropBarKindString", { fg = c.fg })
hi("DropBarKindStruct", { fg = c.fg })
hi("DropBarKindSwitchStatement", { fg = c.fg })
hi("DropBarKindType", { fg = c.fg })
hi("DropBarKindTypeParameter", { fg = c.fg })
hi("DropBarKindUnit", { fg = c.fg })
hi("DropBarKindValue", { fg = c.fg })
hi("DropBarKindVariable", { fg = c.fg })
hi("DropBarKindWhileStatement", { fg = c.fg })
hi("DropBarMenuHoverIcon", { reverse = true })
hi("DropBarMenuHoverSymbol", { bold = true })
hi("EndOfBuffer", { fg = c.surface1 })
hi("Error", { fg = c.red })
hi("ErrorMsg", { fg = c.red, bold = true, italic = true })
hi("Exception", { fg = c.magenta })
hi("FlashBackdrop", { fg = c.gray })
hi("FlashCurrent", { fg = c.yellow, bg = c.bg })
hi("FlashLabel", { fg = c.green, bg = c.bg, bold = true })
hi("FlashMatch", { fg = c.brcyan, bg = c.bg })
hi("FloatBorder", { fg = c.blue, bg = c.darkbg })
hi("FloatShadow", { bg = c.gray })
hi("FloatShadowThrough", { bg = c.gray })
hi("FloatTitle", { fg = c.subtext0, bg = c.darkbg })
hi("FoldColumn", { fg = c.gray })
hi("Folded", { fg = c.blue, bg = c.surface1 })
hi("Function", { fg = c.blue })
hi("FzfLuaBufFlagAlt", { fg = c.blue })
hi("FzfLuaBufFlagCur", { fg = c.yellow })
hi("FzfLuaBufName", { fg = c.magenta })
hi("FzfLuaBufNr", { fg = c.bryellow })
hi("FzfLuaFzfMatch", { fg = c.blue })
hi("FzfLuaFzfPrompt", { fg = c.blue })
hi("FzfLuaHeaderBind", { fg = c.bryellow })
hi("FzfLuaHeaderText", { fg = c.yellow })
hi("FzfLuaLiveSym", { fg = c.yellow })
hi("FzfLuaPathColNr", { fg = c.blue })
hi("FzfLuaPathLineNr", { fg = c.green })
hi("FzfLuaTabMarker", { fg = c.bryellow })
hi("FzfLuaTabTitle", { fg = c.cyan })
hi("GitSignsAdd", { fg = c.green })
hi("GitSignsAddInline", { bg = c.surface2 })
hi("GitSignsChange", { fg = c.bryellow })
hi("GitSignsChangeInline", { bg = c.surface0 })
hi("GitSignsCurrentLineBlame", { fg = c.surface1 })
hi("GitSignsDelete", { fg = c.red })
hi("GitSignsDeleteInline", { bg = c.surface2 })
hi("GlyphPalette1", { fg = c.red })
hi("GlyphPalette2", { fg = c.brgreen })
hi("GlyphPalette3", { fg = c.bryellow })
hi("GlyphPalette4", { fg = c.blue })
hi("GlyphPalette6", { fg = c.brgreen })
hi("GlyphPalette7", { fg = c.fg })
hi("GlyphPalette9", { fg = c.red })
hi("IblIndent", { fg = c.surface0 })
hi("IblScope", { fg = c.fg })
hi("Identifier", { fg = c.bryellow })
hi("IlluminatedWordRead", { bg = c.surface0 })
hi("IlluminatedWordText", { bg = c.surface0 })
hi("IlluminatedWordWrite", { bg = c.surface0 })
hi("IncSearch", { fg = c.darkbg, bg = c.brcyan })
hi("Include", { fg = c.magenta })
hi("Italic", { italic = true })
hi("Keyword", { fg = c.magenta })
hi("Label", { fg = c.brcyan })
hi("LineNr", { fg = c.surface1 })
hi("LspCodeLens", { fg = c.gray })
hi("LspDiagnosticsDefaultError", { fg = c.red })
hi("LspDiagnosticsDefaultHint", { fg = c.brgreen })
hi("LspDiagnosticsDefaultInformation", { fg = c.cyan })
hi("LspDiagnosticsDefaultWarning", { fg = c.bryellow })
hi("LspDiagnosticsError", { fg = c.red })
hi("LspDiagnosticsHint", { fg = c.brgreen })
hi("LspDiagnosticsInformation", { fg = c.cyan })
hi("LspDiagnosticsUnderlineError", { sp = c.red, underline = true })
hi("LspDiagnosticsUnderlineHint", { sp = c.brgreen, underline = true })
hi("LspDiagnosticsUnderlineInformation", { sp = c.cyan, underline = true })
hi("LspDiagnosticsUnderlineWarning", { sp = c.bryellow, underline = true })
hi("LspDiagnosticsVirtualTextError", { fg = c.red, italic = true })
hi("LspDiagnosticsVirtualTextHint", { fg = c.brgreen, italic = true })
hi("LspDiagnosticsVirtualTextInformation", { fg = c.cyan, italic = true })
hi("LspDiagnosticsVirtualTextWarning", { fg = c.bryellow, italic = true })
hi("LspDiagnosticsWarning", { fg = c.bryellow })
hi("LspInlayHint", { fg = c.gray, bg = c.surface0 })
hi("LspReferenceRead", { bg = c.surface1 })
hi("LspReferenceText", { bg = c.surface1 })
hi("LspReferenceWrite", { bg = c.surface1 })
hi("LspSignatureActiveParameter", { bg = c.surface0, bold = true })
hi("Macro", { fg = c.magenta })
hi("MatchParen", { fg = c.yellow, bg = c.surface0, bold = true })
hi("MiniAnimateCursor", { reverse = true, nocombine = true })
hi("MiniCompletionActiveParameter", { underline = true })
hi("MiniCursorword", { underline = true })
hi("MiniCursorwordCurrent", { underline = true })
hi("MiniDepsTitleError", { fg = c.bg, bg = c.red })
hi("MiniDepsTitleUpdate", { fg = c.bg, bg = c.green })
hi("MiniDiffSignAdd", { fg = c.green })
hi("MiniDiffSignChange", { fg = c.bryellow })
hi("MiniDiffSignDelete", { fg = c.red })
hi("MiniFilesFile", { fg = c.fg })
hi("MiniFilesTitleFocused", { fg = c.subtext0, bg = c.darkbg, bold = true })
hi("MiniHipatternsFixme", { fg = c.bg, bg = c.red, bold = true })
hi("MiniHipatternsHack", { fg = c.bg, bg = c.bryellow, bold = true })
hi("MiniHipatternsNote", { fg = c.bg, bg = c.cyan, bold = true })
hi("MiniHipatternsTodo", { fg = c.bg, bg = c.brgreen, bold = true })
hi("MiniIconsAzure", { fg = c.brcyan })
hi("MiniIconsBlue", { fg = c.blue })
hi("MiniIconsCyan", { fg = c.brgreen })
hi("MiniIconsGreen", { fg = c.green })
hi("MiniIconsGrey", { fg = c.fg })
hi("MiniIconsOrange", { fg = c.yellow })
hi("MiniIconsPurple", { fg = c.magenta })
hi("MiniIconsRed", { fg = c.red })
hi("MiniIconsYellow", { fg = c.bryellow })
hi("MiniIndentscopeSymbol", { fg = c.brblack })
hi("MiniJump", { fg = c.brblack, bg = c.brmag })
hi("MiniJump2dDim", { fg = c.gray })
hi("MiniJump2dSpot", { fg = c.yellow, bg = c.bg, bold = true, underline = true })
hi("MiniJump2dSpotAhead", { fg = c.brgreen, bg = c.darkbg })
hi("MiniJump2dSpotUnique", { fg = c.cyan, bg = c.bg, bold = true })
hi("MiniPickBorderText", { fg = c.magenta, bg = c.darkbg })
hi("MiniPickMatchCurrent", { fg = c.bryellow, bg = c.surface0, bold = true })
hi("MiniPickPrompt", { fg = c.fg, bg = c.darkbg })
hi("MiniPickPromptCaret", { fg = c.bryellow, bg = c.darkbg })
hi("MiniPickPromptPrefix", { fg = c.bryellow, bg = c.darkbg })
hi("MiniStarterFooter", { fg = c.bryellow, italic = true })
hi("MiniStarterHeader", { fg = c.blue })
hi("MiniStarterInactive", { fg = c.surface2, italic = true })
hi("MiniStarterItem", { fg = c.fg })
hi("MiniStarterItemBullet", { fg = c.blue })
hi("MiniStarterItemPrefix", { fg = c.brmag })
hi("MiniStarterQuery", { fg = c.green })
hi("MiniStarterSection", { fg = c.bryellow })
hi("MiniStatuslineDevinfo", { fg = c.subtext1, bg = c.surface1 })
hi("MiniStatuslineFileinfo", { fg = c.subtext1, bg = c.surface1 })
hi("MiniStatuslineFilename", { fg = c.fg, bg = c.darkbg })
hi("MiniStatuslineInactive", { fg = c.blue, bg = c.darkbg })
hi("MiniStatuslineModeCommand", { fg = c.bg, bg = c.yellow, bold = true })
hi("MiniStatuslineModeInsert", { fg = c.bg, bg = c.green, bold = true })
hi("MiniStatuslineModeNormal", { fg = c.darkbg, bg = c.blue, bold = true })
hi("MiniStatuslineModeOther", { fg = c.bg, bg = c.brgreen, bold = true })
hi("MiniStatuslineModeReplace", { fg = c.bg, bg = c.red, bold = true })
hi("MiniStatuslineModeVisual", { fg = c.bg, bg = c.magenta, bold = true })
hi("MiniSurround", { fg = c.surface1, bg = c.brmag })
hi("MiniTablineCurrent", { fg = c.fg, bg = c.bg, sp = c.red, bold = true, italic = true, underline = true })
hi("MiniTablineFill", { bg = c.bg })
hi("MiniTablineHidden", { fg = c.fg, bg = c.darkbg })
hi("MiniTablineModifiedCurrent", { fg = c.red, bold = true, italic = true })
hi("MiniTablineModifiedHidden", { fg = c.red })
hi("MiniTablineModifiedVisible", { fg = c.red })
hi("MiniTablineTabpagesection", { fg = c.surface1, bg = c.bg })
hi("MiniTestEmphasis", { bold = true })
hi("MiniTestFail", { fg = c.red, bold = true })
hi("MiniTestPass", { fg = c.green, bold = true })
hi("MiniTrailspace", { bg = c.red })
hi("ModeMsg", { fg = c.fg, bold = true })
hi("MoreMsg", { fg = c.blue })
hi("NeoTreeDimText", { fg = c.brblack })
hi("NeoTreeDirectoryIcon", { fg = c.blue })
hi("NeoTreeDirectoryName", { fg = c.blue })
hi("NeoTreeExpander", { fg = c.gray })
hi("NeoTreeFileNameOpened", { fg = c.brmag })
hi("NeoTreeFilterTerm", { fg = c.green, bold = true })
hi("NeoTreeGitAdded", { fg = c.green })
hi("NeoTreeGitConflict", { fg = c.red })
hi("NeoTreeGitDeleted", { fg = c.red })
hi("NeoTreeGitIgnored", { fg = c.gray })
hi("NeoTreeGitModified", { fg = c.bryellow })
hi("NeoTreeGitStaged", { fg = c.green })
hi("NeoTreeGitUnstaged", { fg = c.red })
hi("NeoTreeGitUntracked", { fg = c.magenta })
hi("NeoTreeIndentMarker", { fg = c.gray })
hi("NeoTreeModified", { fg = c.yellow })
hi("NeoTreeNormal", { fg = c.fg, bg = c.darkbg })
hi("NeoTreeNormalNC", { fg = c.fg, bg = c.darkbg })
hi("NeoTreeRootName", { fg = c.blue, bold = true })
hi("NeoTreeStatusLineNC", { fg = c.darkbg, bg = c.darkbg })
hi("NeoTreeSymbolicLinkTarget", { fg = c.brmag })
hi("NeoTreeTabActive", { fg = c.brcyan, bg = c.darkbg, bold = true })
hi("NeoTreeTabInactive", { fg = c.gray, bg = c.bg })
hi("NeoTreeTabSeparatorActive", { fg = c.darkbg, bg = c.darkbg })
hi("NeoTreeTabSeparatorInactive", { fg = c.bg, bg = c.bg })
hi("NeoTreeTitleBar", { fg = c.darkbg, bg = c.blue })
hi("NeoTreeVertSplit", { fg = c.bg, bg = c.bg })
hi("NeoTreeWinSeparator", { fg = c.bg, bg = c.bg })
hi("NeogitBranch", { fg = c.yellow, bold = true })
hi("NeogitChangeAdded", { fg = c.green, bold = true })
hi("NeogitChangeBothModified", { fg = c.bryellow, bold = true })
hi("NeogitChangeCopied", { fg = c.brmag, bold = true })
hi("NeogitChangeDeleted", { fg = c.red, bold = true })
hi("NeogitChangeModified", { fg = c.blue, bold = true })
hi("NeogitChangeNewFile", { fg = c.green, bold = true })
hi("NeogitChangeRenamed", { fg = c.magenta, bold = true })
hi("NeogitChangeUpdated", { fg = c.yellow, bold = true })
hi("NeogitCommitViewHeader", { fg = c.blue, bg = c.surface1 })
hi("NeogitDiffAdd", { fg = c.green, bg = c.surface0 })
hi("NeogitDiffAddHighlight", { fg = c.green, bg = c.surface1 })
hi("NeogitDiffContext", { bg = c.bg })
hi("NeogitDiffContextHighlight", { bg = c.surface0 })
hi("NeogitDiffDelete", { fg = c.red, bg = c.surface0 })
hi("NeogitDiffDeleteHighlight", { fg = c.brred, bg = c.surface1 })
hi("NeogitDiffHeader", { fg = c.blue, bg = c.bg, bold = true })
hi("NeogitDiffHeaderHighlight", { fg = c.yellow, bg = c.bg, bold = true })
hi("NeogitFilePath", { fg = c.blue, italic = true })
hi("NeogitGraphBlue", { fg = c.blue })
hi("NeogitGraphBoldBlue", { fg = c.blue, bold = true })
hi("NeogitGraphBoldCyan", { fg = c.blue, bold = true })
hi("NeogitGraphBoldGray", { fg = c.subtext1, bold = true })
hi("NeogitGraphBoldGreen", { fg = c.green, bold = true })
hi("NeogitGraphBoldPurple", { fg = c.brcyan, bold = true })
hi("NeogitGraphBoldRed", { fg = c.red, bold = true })
hi("NeogitGraphBoldWhite", { bold = true })
hi("NeogitGraphBoldYellow", { fg = c.bryellow, bold = true })
hi("NeogitGraphCyan", { fg = c.blue })
hi("NeogitGraphGray", { fg = c.subtext1 })
hi("NeogitGraphGreen", { fg = c.green })
hi("NeogitGraphOrange", { fg = c.yellow })
hi("NeogitGraphPurple", { fg = c.brcyan })
hi("NeogitGraphRed", { fg = c.red })
hi("NeogitGraphWhite", { fg = c.bg })
hi("NeogitGraphYellow", { fg = c.bryellow })
hi("NeogitHunkHeader", { fg = c.gray, bg = c.surface0 })
hi("NeogitHunkHeaderHighlight", { fg = c.blue, bg = c.surface1 })
hi("NeogitNotificationError", { fg = c.red })
hi("NeogitNotificationInfo", { fg = c.blue })
hi("NeogitNotificationWarning", { fg = c.bryellow })
hi("NeogitPopupActionKey", { fg = c.brcyan })
hi("NeogitPopupBold", { bold = true })
hi("NeogitPopupConfigKey", { fg = c.brcyan })
hi("NeogitPopupOptionKey", { fg = c.brcyan })
hi("NeogitPopupSwitchKey", { fg = c.brcyan })
hi("NeogitRebasing", { fg = c.magenta, bold = true })
hi("NeogitRecentcommits", { fg = c.magenta, bold = true })
hi("NeogitRemote", { fg = c.green, bold = true })
hi("NeogitSectionHeader", { fg = c.magenta, bold = true })
hi("NeogitStagedchanges", { fg = c.magenta, bold = true })
hi("NeogitStashes", { fg = c.magenta, bold = true })
hi("NeogitTagDistance", { fg = c.blue })
hi("NeogitTagName", { fg = c.bryellow })
hi("NeogitUnmergedchanges", { fg = c.magenta, bold = true })
hi("NeogitUnpulledchanges", { fg = c.magenta, bold = true })
hi("NeogitUnpushedTo", { fg = c.brcyan, bold = true })
hi("NeogitUnstagedchanges", { fg = c.magenta, bold = true })
hi("NeogitUntrackedfiles", { fg = c.magenta, bold = true })
hi("NonText", { fg = c.gray })
hi("Normal", { fg = c.fg, bg = c.bg })
hi("NormalFloat", { fg = c.fg, bg = c.darkbg })
hi("NormalNC", { fg = c.fg, bg = c.bg })
hi("NormalSB", { fg = c.fg, bg = c.darker })
hi("Number", { fg = c.yellow })
hi("NvimInternalError", { fg = c.red, bg = c.red })
hi("NvimTreeEmptyFolderName", { fg = c.blue })
hi("NvimTreeFolderIcon", { fg = c.blue })
hi("NvimTreeFolderName", { fg = c.blue })
hi("NvimTreeGitDeleted", { fg = c.red })
hi("NvimTreeGitDirty", { fg = c.bryellow })
hi("NvimTreeGitNew", { fg = c.blue })
hi("NvimTreeImageFile", { fg = c.fg })
hi("NvimTreeIndentMarker", { fg = c.gray })
hi("NvimTreeNormal", { fg = c.fg, bg = c.darkbg })
hi("NvimTreeOpenedFile", { fg = c.brmag })
hi("NvimTreeOpenedFolderName", { fg = c.blue })
hi("NvimTreeRootFolder", { fg = c.brcyan, bold = true })
hi("NvimTreeSpecialFile", { fg = c.bryellow })
hi("NvimTreeStatuslineNc", { fg = c.darkbg, bg = c.darkbg })
hi("NvimTreeSymlink", { fg = c.brmag })
hi("NvimTreeWinSeparator", { fg = c.bg, bg = c.bg })
hi("Operator", { fg = c.cyan })
hi("Pmenu", { fg = c.brblack, bg = c.darkbg })
hi("PmenuExtra", { fg = c.gray })
hi("PmenuExtraSel", { fg = c.gray, bg = c.surface0, bold = true })
hi("PmenuMatch", { fg = c.fg, bold = true })
hi("PmenuMatchSel", { bold = true })
hi("PmenuSbar", { bg = c.surface0 })
hi("PmenuSel", { bg = c.surface0, bold = true })
hi("PmenuThumb", { bg = c.gray })
hi("PreInsert", { fg = c.brblack })
hi("PreProc", { fg = c.brmag })
hi("Question", { fg = c.blue })
hi("QuickFixLine", { bg = c.surface0, bold = true })
hi("RainbowDelimiterBlue", { fg = c.blue })
hi("RainbowDelimiterCyan", { fg = c.brgreen })
hi("RainbowDelimiterGreen", { fg = c.green })
hi("RainbowDelimiterOrange", { fg = c.yellow })
hi("RainbowDelimiterRed", { fg = c.red })
hi("RainbowDelimiterViolet", { fg = c.magenta })
hi("RainbowDelimiterYellow", { fg = c.bryellow })
hi("RedrawDebugClear", { bg = c.surface0 })
hi("RedrawDebugComposed", { bg = c.bg })
hi("RedrawDebugNormal", { reverse = true })
hi("RedrawDebugRecompose", { bg = c.darkbg })
hi("Removed", { fg = c.bryellow })
hi("RenderMarkdownBullet", { fg = c.cyan })
hi("RenderMarkdownCode", { bg = c.darkbg })
hi("RenderMarkdownCodeInline", { bg = c.surface0 })
hi("RenderMarkdownError", { fg = c.red })
hi("RenderMarkdownH1", { fg = c.red })
hi("RenderMarkdownH1Bg", { bg = c.surface0 })
hi("RenderMarkdownH2", { fg = c.yellow })
hi("RenderMarkdownH2Bg", { bg = c.surface0 })
hi("RenderMarkdownH3", { fg = c.bryellow })
hi("RenderMarkdownH3Bg", { bg = c.surface0 })
hi("RenderMarkdownH4", { fg = c.green })
hi("RenderMarkdownH4Bg", { bg = c.surface0 })
hi("RenderMarkdownH5", { fg = c.brcyan })
hi("RenderMarkdownH5Bg", { bg = c.surface0 })
hi("RenderMarkdownH6", { fg = c.brcyan })
hi("RenderMarkdownH6Bg", { bg = c.surface0 })
hi("RenderMarkdownHint", { fg = c.brgreen })
hi("RenderMarkdownInfo", { fg = c.cyan })
hi("RenderMarkdownSuccess", { fg = c.green })
hi("RenderMarkdownTableHead", { fg = c.blue })
hi("RenderMarkdownTableRow", { fg = c.brcyan })
hi("RenderMarkdownWarn", { fg = c.bryellow })
hi("Repeat", { fg = c.magenta })
hi("Search", { fg = c.fg, bg = c.surface1 })
hi("SignColumn", { fg = c.surface1 })
hi("SignColumnSB", { fg = c.surface1, bg = c.darker })
hi("Special", { fg = c.brmag })
hi("SpellBad", { sp = c.red, undercurl = true })
hi("SpellCap", { sp = c.bryellow, undercurl = true })
hi("SpellLocal", { sp = c.blue, undercurl = true })
hi("SpellRare", { sp = c.green, undercurl = true })
hi("Statement", { fg = c.magenta })
hi("StatusLine", { fg = c.fg, bg = c.darkbg })
hi("StatusLineNC", { fg = c.surface1, bg = c.darkbg })
hi("StorageClass", { fg = c.bryellow })
hi("String", { fg = c.green })
hi("Structure", { fg = c.bryellow })
hi("Substitute", { fg = c.brmag, bg = c.surface1 })
hi("TabLine", { fg = c.gray, bg = c.darker })
hi("TabLineFill", { bg = c.darkbg })
hi("Tag", { fg = c.brcyan, bold = true })
hi("TelescopeMatching", { fg = c.blue })
hi("TelescopePromptPrefix", { fg = c.bryellow })
hi("TelescopeSelection", { fg = c.bryellow, bg = c.surface0, bold = true })
hi("TelescopeSelectionCaret", { fg = c.bryellow, bg = c.surface0 })
hi("TermCursor", { fg = c.bg, bg = c.bryellow })
hi("TermCursorNC", { fg = c.bg, bg = c.brblack })
hi("Title", { fg = c.blue, bold = true })
hi("Todo", { fg = c.bg, bg = c.bryellow, bold = true })
hi("TreesitterContext", { fg = c.fg, bg = c.darkbg })
hi("TreesitterContextBottom", { sp = c.surface0, underline = true })
hi("TreesitterContextLineNumber", { fg = c.surface1, bg = c.darkbg })
hi("Type", { fg = c.bryellow })
hi("UfoFoldedEllipsis", { fg = c.darker, bg = c.blue })
hi("UfoFoldedFg", { fg = c.brcyan })
hi("Underlined", { underline = true })
hi("VertSplit", { fg = c.darker })
hi("Visual", { bg = c.surface1, bold = true })
hi("VisualNOS", { bg = c.surface1, bold = true })
hi("WarningMsg", { fg = c.bryellow })
hi("Whitespace", { fg = c.surface1 })
hi("WildMenu", { bg = c.gray })
hi("WinBar", { fg = c.bryellow })
hi("WinSeparator", { fg = c.darker })
hi("csvCol0", { fg = c.red })
hi("csvCol1", { fg = c.yellow })
hi("csvCol2", { fg = c.bryellow })
hi("csvCol3", { fg = c.green })
hi("csvCol4", { fg = c.cyan })
hi("csvCol5", { fg = c.blue })
hi("csvCol6", { fg = c.brcyan })
hi("csvCol7", { fg = c.magenta })
hi("csvCol8", { fg = c.brmag })
hi("debugBreakpoint", { fg = c.gray, bg = c.bg })
hi("debugPC", { bg = c.darker })
hi("diffAdded", { fg = c.green })
hi("diffChanged", { fg = c.blue })
hi("diffFile", { fg = c.blue })
hi("diffIndexLine", { fg = c.brgreen })
hi("diffLine", { fg = c.gray })
hi("diffNewFile", { fg = c.yellow })
hi("diffOldFile", { fg = c.bryellow })
hi("diffRemoved", { fg = c.red })
hi("gitcommitSummary", { fg = c.bryellow, italic = true })
hi("healthError", { fg = c.red })
hi("healthSuccess", { fg = c.brgreen })
hi("healthWarning", { fg = c.bryellow })
hi("htmlH1", { fg = c.brmag, bold = true })
hi("htmlH2", { fg = c.blue, bold = true })
hi("illuminatedCurWord", { bg = c.surface1 })
hi("illuminatedWord", { bg = c.surface1 })
hi("lCursor", { fg = c.bg, bg = c.bryellow })
hi("markdownCode", { fg = c.fg })
hi("markdownCodeBlock", { fg = c.fg })
hi("markdownHeadingDelimiter", { fg = c.yellow, bold = true })
hi("markdownLinkText", { fg = c.blue, underline = true })
hi("mkdCodeDelimiter", { fg = c.fg, bg = c.bg })
hi("mkdCodeEnd", { fg = c.bryellow, bold = true })
hi("mkdCodeStart", { fg = c.bryellow, bold = true })
hi("qfFileName", { fg = c.blue })
hi("qfLineNr", { fg = c.bryellow })
hi("rainbow1", { fg = c.red })
hi("rainbow2", { fg = c.yellow })
hi("rainbow3", { fg = c.bryellow })
hi("rainbow4", { fg = c.green })
hi("rainbow5", { fg = c.brcyan })
hi("rainbow6", { fg = c.brcyan })

-- Highlight groups (links)
hi("@attribute", { link = "Constant" })
hi("@attribute.builtin", { link = "Special" })
hi("@boolean", { link = "Boolean" })
hi("@character", { link = "Character" })
hi("@character.special", { link = "SpecialChar" })
hi("@comment", { link = "Comment" })
hi("@comment.documentation", { link = "Comment" })
hi("@conditional", { link = "Conditional" })
hi("@constant", { link = "Constant" })
hi("@constant.macro", { link = "Macro" })
hi("@constructor.lua", { link = "@punctuation.bracket" })
hi("@define", { link = "Define" })
hi("@diff.delta", { link = "diffChanged" })
hi("@diff.minus", { link = "diffRemoved" })
hi("@diff.plus", { link = "diffAdded" })
hi("@error", { link = "Error" })
hi("@exception", { link = "Exception" })
hi("@float", { link = "Float" })
hi("@function", { link = "Function" })
hi("@function.call", { link = "Function" })
hi("@function.method", { link = "Function" })
hi("@function.method.call", { link = "Function" })
hi("@function.method.call.php", { link = "Function" })
hi("@function.method.php", { link = "Function" })
hi("@include", { link = "Include" })
hi("@keyword", { link = "Keyword" })
hi("@keyword.conditional", { link = "Conditional" })
hi("@keyword.conditional.ternary", { link = "Operator" })
hi("@keyword.coroutine", { link = "Keyword" })
hi("@keyword.debug", { link = "Exception" })
hi("@keyword.directive", { link = "PreProc" })
hi("@keyword.directive.css", { link = "Keyword" })
hi("@keyword.directive.define", { link = "Define" })
hi("@keyword.exception", { link = "Exception" })
hi("@keyword.import", { link = "Include" })
hi("@keyword.modifier", { link = "Keyword" })
hi("@keyword.repeat", { link = "Repeat" })
hi("@keyword.storage", { link = "Keyword" })
hi("@keyword.type", { link = "Keyword" })
hi("@label", { link = "Label" })
hi("@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi("@lsp.type.class", { link = "@type" })
hi("@lsp.type.comment", { link = "@comment" })
hi("@lsp.type.decorator", { link = "@attribute" })
hi("@lsp.type.enum", { link = "@type" })
hi("@lsp.type.event", { link = "@type" })
hi("@lsp.type.function", { link = "@function" })
hi("@lsp.type.interface", { link = "@type" })
hi("@lsp.type.keyword", { link = "@keyword" })
hi("@lsp.type.macro", { link = "@constant.macro" })
hi("@lsp.type.method", { link = "@function.method" })
hi("@lsp.type.modifier", { link = "@type.qualifier" })
hi("@lsp.type.namespace", { link = "@module" })
hi("@lsp.type.number", { link = "@number" })
hi("@lsp.type.operator", { link = "@operator" })
hi("@lsp.type.parameter", { link = "@variable.parameter" })
hi("@lsp.type.property", { link = "@property" })
hi("@lsp.type.regexp", { link = "@string.regexp" })
hi("@lsp.type.string", { link = "@string" })
hi("@lsp.type.struct", { link = "@type" })
hi("@lsp.type.type", { link = "@type" })
hi("@lsp.type.typeParameter", { link = "@type.definition" })
hi("@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi("@markup.heading.1.html", { link = "@markup" })
hi("@markup.heading.1.markdown", { link = "rainbow1" })
hi("@markup.heading.2.html", { link = "@markup" })
hi("@markup.heading.2.markdown", { link = "rainbow2" })
hi("@markup.heading.3.html", { link = "@markup" })
hi("@markup.heading.3.markdown", { link = "rainbow3" })
hi("@markup.heading.4.html", { link = "@markup" })
hi("@markup.heading.4.markdown", { link = "rainbow4" })
hi("@markup.heading.5.html", { link = "@markup" })
hi("@markup.heading.5.markdown", { link = "rainbow5" })
hi("@markup.heading.6.html", { link = "@markup" })
hi("@markup.heading.6.markdown", { link = "rainbow6" })
hi("@markup.heading.html", { link = "@markup" })
hi("@markup.underline", { link = "Underlined" })
hi("@method", { link = "Function" })
hi("@method.call", { link = "Function" })
hi("@method.call.php", { link = "Function" })
hi("@method.php", { link = "Function" })
hi("@module.builtin", { link = "Special" })
hi("@number", { link = "Number" })
hi("@number.float", { link = "Float" })
hi("@operator", { link = "Operator" })
hi("@preproc", { link = "PreProc" })
hi("@punctuation", { link = "Delimiter" })
hi("@punctuation.delimiter", { link = "Delimiter" })
hi("@punctuation.delimiter.regex", { link = "@string.regexp" })
hi("@punctuation.special", { link = "Special" })
hi("@repeat", { link = "Repeat" })
hi("@storageclass", { link = "Keyword" })
hi("@string", { link = "String" })
hi("@string.special", { link = "Special" })
hi("@string.special.path", { link = "Special" })
hi("@text.diff.add", { link = "diffAdded" })
hi("@text.diff.delete", { link = "diffRemoved" })
hi("@text.title.1.markdown", { link = "rainbow1" })
hi("@text.title.2.markdown", { link = "rainbow2" })
hi("@text.title.3.markdown", { link = "rainbow3" })
hi("@text.title.4.markdown", { link = "rainbow4" })
hi("@text.title.5.markdown", { link = "rainbow5" })
hi("@text.title.6.markdown", { link = "rainbow6" })
hi("@text.underline", { link = "Underlined" })
hi("@type", { link = "Type" })
hi("@type.definition", { link = "Type" })
hi("@type.qualifier", { link = "Keyword" })
hi("@variable.parameter.builtin", { link = "Special" })
hi("BlinkCmpDoc", { link = "NormalFloat" })
hi("BlinkCmpDocBorder", { link = "FloatBorder" })
hi("BlinkCmpLabelDescription", { link = "PmenuExtra" })
hi("BlinkCmpLabelDetail", { link = "PmenuExtra" })
hi("BlinkCmpLabelMatch", { link = "PmenuMatch" })
hi("BlinkCmpMenu", { link = "Pmenu" })
hi("BlinkCmpSignatureHelpBorder", { link = "FloatBorder" })
hi("ComplHintMore", { link = "Question" })
hi("ComplMatchIns", { link = "PreInsert" })
hi("CursorLineFold", { link = "FoldColumn" })
hi("CursorLineSign", { link = "SignColumn" })
hi("DapUIFloatBorder", { link = "FloatBorder" })
hi("DapUIPlayPauseNC", { link = "DapUIPlayPause" })
hi("DapUIRestartNC", { link = "DapUIRestart" })
hi("DapUIStepBackNC", { link = "DapUIStepBack" })
hi("DapUIStepIntoNC", { link = "DapUIStepInto" })
hi("DapUIStepOutNC", { link = "DapUIStepOut" })
hi("DapUIStepOverNC", { link = "DapUIStepOver" })
hi("DapUIStopNC", { link = "DapUIStop" })
hi("DapUIUnavailableNC", { link = "DapUIUnavailable" })
hi("Debug", { link = "Special" })
hi("Define", { link = "PreProc" })
hi("DiagnosticUnnecessary", { link = "Comment" })
hi("DiagnosticVirtualLinesError", { link = "DiagnosticError" })
hi("DiagnosticVirtualLinesHint", { link = "DiagnosticHint" })
hi("DiagnosticVirtualLinesInfo", { link = "DiagnosticInfo" })
hi("DiagnosticVirtualLinesOk", { link = "DiagnosticOk" })
hi("DiagnosticVirtualLinesWarn", { link = "DiagnosticWarn" })
hi("DropBarMenuHoverEntry", { link = "Visual" })
hi("FlashPrompt", { link = "NormalFloat" })
hi("Float", { link = "Number" })
hi("FloatFooter", { link = "FloatTitle" })
hi("FzfLuaBorder", { link = "FloatBorder" })
hi("FzfLuaDirPart", { link = "NonText" })
hi("FzfLuaNormal", { link = "NormalFloat" })
hi("FzfLuaTitle", { link = "FloatTitle" })
hi("GitSignsAddPreview", { link = "DiffAdd" })
hi("GitSignsDeletePreview", { link = "DiffDelete" })
hi("Ignore", { link = "Normal" })
hi("LineNrAbove", { link = "LineNr" })
hi("LineNrBelow", { link = "LineNr" })
hi("LspCodeLensSeparator", { link = "LspCodeLens" })
hi("LspInfoBorder", { link = "FloatBorder" })
hi("LspReferenceTarget", { link = "LspReferenceText" })
hi("MiniAnimateNormalFloat", { link = "NormalFloat" })
hi("MiniClueBorder", { link = "FloatBorder" })
hi("MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi("MiniClueDescSingle", { link = "NormalFloat" })
hi("MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi("MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi("MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi("MiniClueTitle", { link = "FloatTitle" })
hi("MiniDepsChangeAdded", { link = "diffAdded" })
hi("MiniDepsChangeRemoved", { link = "diffRemoved" })
hi("MiniDepsHint", { link = "DiagnosticHint" })
hi("MiniDepsInfo", { link = "DiagnosticInfo" })
hi("MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi("MiniDepsPlaceholder", { link = "Comment" })
hi("MiniDepsTitle", { link = "Title" })
hi("MiniDepsTitleSame", { link = "DiffText" })
hi("MiniDiffOverAdd", { link = "DiffAdd" })
hi("MiniDiffOverChange", { link = "DiffText" })
hi("MiniDiffOverContext", { link = "DiffChange" })
hi("MiniDiffOverDelete", { link = "DiffDelete" })
hi("MiniFilesBorder", { link = "FloatBorder" })
hi("MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi("MiniFilesCursorLine", { link = "CursorLine" })
hi("MiniFilesDirectory", { link = "Directory" })
hi("MiniFilesNormal", { link = "NormalFloat" })
hi("MiniFilesTitle", { link = "FloatTitle" })
hi("MiniMapNormal", { link = "NormalFloat" })
hi("MiniMapSymbolCount", { link = "Special" })
hi("MiniMapSymbolLine", { link = "Title" })
hi("MiniMapSymbolView", { link = "Delimiter" })
hi("MiniNotifyBorder", { link = "FloatBorder" })
hi("MiniNotifyNormal", { link = "NormalFloat" })
hi("MiniNotifyTitle", { link = "FloatTitle" })
hi("MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi("MiniPickBorder", { link = "FloatBorder" })
hi("MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi("MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi("MiniPickIconDirectory", { link = "Directory" })
hi("MiniPickIconFile", { link = "MiniPickNormal" })
hi("MiniPickMatchMarked", { link = "Visual" })
hi("MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi("MiniPickNormal", { link = "NormalFloat" })
hi("MiniPickPreviewLine", { link = "CursorLine" })
hi("MiniPickPreviewRegion", { link = "IncSearch" })
hi("MsgSeparator", { link = "WinSeparator" })
hi("NeoTreeFloatBorder", { link = "FloatBorder" })
hi("NeoTreeFloatTitle", { link = "FloatTitle" })
hi("NeogitObjectId", { link = "Comment" })
hi("NeogitRebaseDone", { link = "Comment" })
hi("NeogitStash", { link = "Comment" })
hi("NeogitUnmergedInto", { link = "Function" })
hi("NeogitUnpulledFrom", { link = "Function" })
hi("NeogitWinSeparator", { link = "WinSeparator" })
hi("NvimAnd", { link = "NvimBinaryOperator" })
hi("NvimArrow", { link = "Delimiter" })
hi("NvimAssignment", { link = "Operator" })
hi("NvimAssignmentWithAddition", { link = "NvimAugmentedAssignment" })
hi("NvimAssignmentWithConcatenation", { link = "NvimAugmentedAssignment" })
hi("NvimAssignmentWithSubtraction", { link = "NvimAugmentedAssignment" })
hi("NvimAugmentedAssignment", { link = "NvimAssignment" })
hi("NvimBinaryMinus", { link = "NvimBinaryOperator" })
hi("NvimBinaryOperator", { link = "NvimOperator" })
hi("NvimBinaryPlus", { link = "NvimBinaryOperator" })
hi("NvimCallingParenthesis", { link = "NvimParenthesis" })
hi("NvimColon", { link = "Delimiter" })
hi("NvimComma", { link = "Delimiter" })
hi("NvimComparison", { link = "NvimBinaryOperator" })
hi("NvimComparisonModifier", { link = "NvimComparison" })
hi("NvimConcat", { link = "NvimBinaryOperator" })
hi("NvimConcatOrSubscript", { link = "NvimConcat" })
hi("NvimContainer", { link = "NvimParenthesis" })
hi("NvimCurly", { link = "NvimSubscript" })
hi("NvimDict", { link = "NvimContainer" })
hi("NvimDivision", { link = "NvimBinaryOperator" })
hi("NvimDoubleQuote", { link = "NvimStringQuote" })
hi("NvimDoubleQuotedBody", { link = "NvimStringBody" })
hi("NvimDoubleQuotedEscape", { link = "NvimStringSpecial" })
hi("NvimDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hi("NvimEnvironmentName", { link = "NvimIdentifier" })
hi("NvimEnvironmentSigil", { link = "NvimOptionSigil" })
hi("NvimFigureBrace", { link = "NvimInternalError" })
hi("NvimFloat", { link = "NvimNumber" })
hi("NvimIdentifier", { link = "Identifier" })
hi("NvimIdentifierKey", { link = "NvimIdentifier" })
hi("NvimIdentifierName", { link = "NvimIdentifier" })
hi("NvimIdentifierScope", { link = "NvimIdentifier" })
hi("NvimIdentifierScopeDelimiter", { link = "NvimIdentifier" })
hi("NvimInvalid", { link = "Error" })
hi("NvimInvalidAnd", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidArrow", { link = "NvimInvalidDelimiter" })
hi("NvimInvalidAssignment", { link = "NvimInvalid" })
hi("NvimInvalidAssignmentWithAddition", { link = "NvimInvalidAugmentedAssignment" })
hi("NvimInvalidAssignmentWithConcatenation", { link = "NvimInvalidAugmentedAssignment" })
hi("NvimInvalidAssignmentWithSubtraction", { link = "NvimInvalidAugmentedAssignment" })
hi("NvimInvalidAugmentedAssignment", { link = "NvimInvalidAssignment" })
hi("NvimInvalidBinaryMinus", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidBinaryOperator", { link = "NvimInvalidOperator" })
hi("NvimInvalidBinaryPlus", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidCallingParenthesis", { link = "NvimInvalidParenthesis" })
hi("NvimInvalidColon", { link = "NvimInvalidDelimiter" })
hi("NvimInvalidComma", { link = "NvimInvalidDelimiter" })
hi("NvimInvalidComparison", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidComparisonModifier", { link = "NvimInvalidComparison" })
hi("NvimInvalidConcat", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidConcatOrSubscript", { link = "NvimInvalidConcat" })
hi("NvimInvalidContainer", { link = "NvimInvalidParenthesis" })
hi("NvimInvalidCurly", { link = "NvimInvalidSubscript" })
hi("NvimInvalidDelimiter", { link = "NvimInvalid" })
hi("NvimInvalidDict", { link = "NvimInvalidContainer" })
hi("NvimInvalidDivision", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidDoubleQuote", { link = "NvimInvalidStringQuote" })
hi("NvimInvalidDoubleQuotedBody", { link = "NvimInvalidStringBody" })
hi("NvimInvalidDoubleQuotedEscape", { link = "NvimInvalidStringSpecial" })
hi("NvimInvalidDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hi("NvimInvalidEnvironmentName", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidEnvironmentSigil", { link = "NvimInvalidOptionSigil" })
hi("NvimInvalidFigureBrace", { link = "NvimInvalidDelimiter" })
hi("NvimInvalidFloat", { link = "NvimInvalidNumber" })
hi("NvimInvalidIdentifier", { link = "NvimInvalidValue" })
hi("NvimInvalidIdentifierKey", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidIdentifierName", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidIdentifierScope", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidIdentifierScopeDelimiter", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidLambda", { link = "NvimInvalidParenthesis" })
hi("NvimInvalidList", { link = "NvimInvalidContainer" })
hi("NvimInvalidMod", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidMultiplication", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidNestingParenthesis", { link = "NvimInvalidParenthesis" })
hi("NvimInvalidNot", { link = "NvimInvalidUnaryOperator" })
hi("NvimInvalidNumber", { link = "NvimInvalidValue" })
hi("NvimInvalidNumberPrefix", { link = "NvimInvalidNumber" })
hi("NvimInvalidOperator", { link = "NvimInvalid" })
hi("NvimInvalidOptionName", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidOptionScope", { link = "NvimInvalidIdentifierScope" })
hi("NvimInvalidOptionScopeDelimiter", { link = "NvimInvalidIdentifierScopeDelimiter" })
hi("NvimInvalidOptionSigil", { link = "NvimInvalidIdentifier" })
hi("NvimInvalidOr", { link = "NvimInvalidBinaryOperator" })
hi("NvimInvalidParenthesis", { link = "NvimInvalidDelimiter" })
hi("NvimInvalidPlainAssignment", { link = "NvimInvalidAssignment" })
hi("NvimInvalidRegister", { link = "NvimInvalidValue" })
hi("NvimInvalidSingleQuote", { link = "NvimInvalidStringQuote" })
hi("NvimInvalidSingleQuotedBody", { link = "NvimInvalidStringBody" })
hi("NvimInvalidSingleQuotedQuote", { link = "NvimInvalidStringSpecial" })
hi("NvimInvalidSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hi("NvimInvalidSpacing", { link = "ErrorMsg" })
hi("NvimInvalidString", { link = "NvimInvalidValue" })
hi("NvimInvalidStringBody", { link = "NvimStringBody" })
hi("NvimInvalidStringQuote", { link = "NvimInvalidString" })
hi("NvimInvalidStringSpecial", { link = "NvimStringSpecial" })
hi("NvimInvalidSubscript", { link = "NvimInvalidParenthesis" })
hi("NvimInvalidSubscriptBracket", { link = "NvimInvalidSubscript" })
hi("NvimInvalidSubscriptColon", { link = "NvimInvalidSubscript" })
hi("NvimInvalidTernary", { link = "NvimInvalidOperator" })
hi("NvimInvalidTernaryColon", { link = "NvimInvalidTernary" })
hi("NvimInvalidUnaryMinus", { link = "NvimInvalidUnaryOperator" })
hi("NvimInvalidUnaryOperator", { link = "NvimInvalidOperator" })
hi("NvimInvalidUnaryPlus", { link = "NvimInvalidUnaryOperator" })
hi("NvimInvalidValue", { link = "NvimInvalid" })
hi("NvimLambda", { link = "NvimParenthesis" })
hi("NvimList", { link = "NvimContainer" })
hi("NvimMod", { link = "NvimBinaryOperator" })
hi("NvimMultiplication", { link = "NvimBinaryOperator" })
hi("NvimNestingParenthesis", { link = "NvimParenthesis" })
hi("NvimNot", { link = "NvimUnaryOperator" })
hi("NvimNumber", { link = "Number" })
hi("NvimNumberPrefix", { link = "Type" })
hi("NvimOperator", { link = "Operator" })
hi("NvimOptionName", { link = "NvimIdentifier" })
hi("NvimOptionScope", { link = "NvimIdentifierScope" })
hi("NvimOptionScopeDelimiter", { link = "NvimIdentifierScopeDelimiter" })
hi("NvimOptionSigil", { link = "Type" })
hi("NvimOr", { link = "NvimBinaryOperator" })
hi("NvimParenthesis", { link = "Delimiter" })
hi("NvimPlainAssignment", { link = "NvimAssignment" })
hi("NvimRegister", { link = "SpecialChar" })
hi("NvimSingleQuote", { link = "NvimStringQuote" })
hi("NvimSingleQuotedBody", { link = "NvimStringBody" })
hi("NvimSingleQuotedQuote", { link = "NvimStringSpecial" })
hi("NvimSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hi("NvimSpacing", { link = "Normal" })
hi("NvimString", { link = "String" })
hi("NvimStringBody", { link = "NvimString" })
hi("NvimStringQuote", { link = "NvimString" })
hi("NvimStringSpecial", { link = "SpecialChar" })
hi("NvimSubscript", { link = "NvimParenthesis" })
hi("NvimSubscriptBracket", { link = "NvimSubscript" })
hi("NvimSubscriptColon", { link = "NvimSubscript" })
hi("NvimTernary", { link = "NvimOperator" })
hi("NvimTernaryColon", { link = "NvimTernary" })
hi("NvimUnaryMinus", { link = "NvimUnaryOperator" })
hi("NvimUnaryOperator", { link = "NvimOperator" })
hi("NvimUnaryPlus", { link = "NvimUnaryOperator" })
hi("PmenuKind", { link = "Pmenu" })
hi("PmenuKindSel", { link = "PmenuSel" })
hi("PreCondit", { link = "PreProc" })
hi("SnippetTabstop", { link = "Visual" })
hi("SpecialChar", { link = "Special" })
hi("SpecialComment", { link = "Special" })
hi("SpecialKey", { link = "NonText" })
hi("StatusLineTerm", { link = "StatusLine" })
hi("StatusLineTermNC", { link = "StatusLineNC" })
hi("TabLineSel", { link = "Normal" })
hi("TelescopeBorder", { link = "FloatBorder" })
hi("TelescopeNormal", { link = "NormalFloat" })
hi("TelescopePreviewNormal", { link = "TelescopeNormal" })
hi("TelescopePromptNormal", { link = "TelescopeNormal" })
hi("TelescopeResultsNormal", { link = "TelescopeNormal" })
hi("TelescopeTitle", { link = "FloatTitle" })
hi("Typedef", { link = "Type" })
hi("WinBarNC", { link = "WinBar" })
hi("markdownH1", { link = "rainbow1" })
hi("markdownH2", { link = "rainbow2" })
hi("markdownH3", { link = "rainbow3" })
hi("markdownH4", { link = "rainbow4" })
hi("markdownH5", { link = "rainbow5" })
hi("markdownH6", { link = "rainbow6" })
hi("zshKSHFunction", { link = "Function" })

-- Terminal colors
vim.g.terminal_color_0 = c.black
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.magenta
vim.g.terminal_color_6 = c.cyan
vim.g.terminal_color_7 = c.white
vim.g.terminal_color_8 = c.brblack
vim.g.terminal_color_9 = c.brred
vim.g.terminal_color_10 = c.brgreen
vim.g.terminal_color_11 = c.bryellow
vim.g.terminal_color_12 = c.brblue
vim.g.terminal_color_13 = c.brmag
vim.g.terminal_color_14 = c.brcyan
vim.g.terminal_color_15 = c.brwhite
